[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 15.0

[font.bold]
#family = "0xProto"
family = "JetBrains Mono Nerd Font"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrains Mono Nerd Font"


[font.normal]
family = "JetBrains Mono Nerd Font"

style = "Medium"

[font.offset]
x = 0
y = 0

[window]
decorations = "none"
opacity = 0.4
